import React from 'react';
import { Lock } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export default function PrivacyDisclaimer() {
  const { lang } = useLanguage();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 min-h-screen bg-white text-charcoal font-sans">
      
      <div className="space-y-3">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-lavender-100 text-lavender-deep text-xs font-heading font-bold uppercase tracking-wider">
          <Lock className="w-4 h-4 text-lavender-deep" />
          <span>{lang === 'en' ? 'Legal & Privacy Notice' : 'गोपनीयता व कायदेशीर सूचना'}</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-heading font-extrabold text-charcoal">
          {lang === 'en' ? 'Privacy Policy & Legal Disclaimer' : 'गोपनीयता धोरण व कायदेशीर अस्वीकरण'}
        </h1>
      </div>

      <div className="bg-white rounded-3xl border border-lavender-100 p-6 sm:p-8 shadow-xs space-y-6 text-sm text-charcoal-700 leading-relaxed font-normal">
        
        <section className="space-y-2">
          <h2 className="font-heading font-bold text-charcoal text-base">
            {lang === 'en' ? '1. Informational Nature of this Site' : '१. या संकेतस्थळाचे माहितीपूर्ण स्वरूप'}
          </h2>
          <p>
            {lang === 'en' 
              ? 'This portal is a public information and triage platform designed to educate citizens on cyber hygiene, incident classification, and emergency response. This site does NOT process FIR filings, collect victim case data, or store private financial records.'
              : 'हे पोर्टल नागरिकांना सायबर सुरक्षा, गुन्ह्यांचे वर्गीकरण आणि आपत्कालीन उपायांबद्दल माहिती देण्यासाठी बनवले आहे. हे पोर्टल एफआयआर दाखल करत नाही किंवा नागरिकांची कोणतीही वैयक्तिक/बँक माहिती साठवत नाही.'}
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading font-bold text-charcoal text-base">
            {lang === 'en' ? '2. Zero Personal Data Storage' : '२. वैयक्तिक डेटा साठवला जात नाही'}
          </h2>
          <p>
            {lang === 'en'
              ? 'No user accounts, passwords, or personal identity numbers are required or stored on this website. The "What Happened To Me?" questionnaire operates entirely in your browser memory and does not record or transmit your selected answers to any external server.'
              : 'या वेबसाईटवर कोणतेही अकाऊंट, पासवर्ड किंवा ओळखपत्र माहिती आवश्यक नाही. "माझ्यासोबत काय घडले?" प्रश्नावली फक्त तुमच्या ब्राऊजरमध्ये चालते आणि कोणताही डेटा सर्व्हरवर पाठवत नाही.'}
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading font-bold text-charcoal text-base">
            {lang === 'en' ? '3. Non-Legal Determination' : '३. कायदेशीर सल्ला नाही'}
          </h2>
          <p>
            {lang === 'en'
              ? 'The risk scores and diagnostic assessments generated by the triage tool are informational estimates intended to guide emergency triage. They do not constitute formal legal determinations, police investigations, or judicial findings. For official legal proceedings, please register a formal report with the National Cyber Crime Reporting Portal (cybercrime.gov.in) or your local Cyber Police Station.'
              : 'प्रश्नांवलीद्वारे दिलेले निष्कर्ष हे केवळ तातडीच्या मार्गदर्शनासाठी दिलेले अंदाज आहेत. तो कोणताही न्यायालयीन निर्णय किंवा पोलिसांचा अधिकृत निष्कर्ष नाही. अधिकृत तक्रारीसाठी cybercrime.gov.in किंवा स्थानिक सायबर पोलिसांशी संपर्क साधावा.'}
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-heading font-bold text-charcoal text-base">
            {lang === 'en' ? '4. Demonstration Statistics' : '४. प्रात्यक्षिक आकडेवारी'}
          </h2>
          <p>
            {lang === 'en'
              ? 'All statistics presented on the Public Cyber Trend Dashboard are aggregated and anonymized. Sample dataset displays carry explicit "Demonstration Data — for prototype only" badges.'
              : 'डॅशबोर्डवर दर्शवलेली आकडेवारी पूर्णपणे एकत्रित आणि अनामित आहे. प्रात्यक्षिक डेटा स्पष्टपणे लेबलग्रस्त केलेला आहे.'}
          </p>
        </section>

      </div>

    </div>
  );
}


